version: '3'

services:
  overwatch:
    build: .
    container_name: linto-overwatch
    image: linto/overwatch
    env_file: .env
    networks:
      - linto_net
      - internal

networks:
  internal:
  linto_net:
    external: true
